[package]
name = "brick-exec"
version = "0.1.0"
edition = "2021"

[features]
parallel = ["dep:rayon"]

[dependencies]
brick-core = { path = "../brick-core" }
rayon = { version = "1", optional = true }
